Enumerations: 
ActionCardType(extraTurn, connectTiles, removeConnection, moveToTile, loseTurn)
PlayerColor(Blue, Red, Yellow, Green)
CardStatus(inDeck, inPlay)

Classes: 
Tile_O()
Player(int number, PlayerColor color)
Tile(boolean isHidden, boolean isVisited)
ConnectionPiece()
ActionTile(int turnsAsNormalTile)
ActionCard(ActionCardType type, CardStatus status)

Relationships:
1 Tile_O contain 1..32 ActionCard
1 Tile_O contain 32 ConnectionPiece
1 Tile_O contain * Player
1 Tile_O contain *Tile

1 Tile associate *ConnectionPiece
1..4 Tile associate 1 Player
1 ActionTile associate * Tile
1 ActionCard associate 1..4 Player
* Tile associate 1..* Player
1..4 Player associate 1..* Tile
1..2 ConnectionPiece associate 1 Tile