<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ClassDiagram" nsURI="http://www.example.com/ClassDiagram"
    nsPrefix="ClassDiagram">
  <eClassifiers xsi:type="ecore:EEnum" name="DeviceStatus">
    <eLiterals name="Activated"/>
    <eLiterals name="Deactivated"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CommandType">
    <eLiterals name="lockDoor"/>
    <eLiterals name="turnOnHeating"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CommandStatus">
    <eLiterals name="Requested"/>
    <eLiterals name="Completed"/>
    <eLiterals name="Failed"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RuleStatus">
    <eLiterals name="created"/>
    <eLiterals name="edited"/>
    <eLiterals name="activated"/>
    <eLiterals name="deactivated"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BinaryOp">
    <eLiterals name="AND"/>
    <eLiterals name="OR"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SHAS">
    <eStructuralFeatures xsi:type="ecore:EReference" name="SmartHome" eType="#//SmartHome" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="User" eType="#//User" containment="true" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmartHome">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Address" eType="#//Address" containment="true" lowerBound="0" upperBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Room" eType="#//Room" containment="true" lowerBound="0" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ActivityLog" eType="#//ActivityLog" containment="true" lowerBound="0" upperBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="User" eType="#//User" containment="false" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="User">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SmartHome" eType="#//SmartHome" containment="false" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Address">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="city" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="postalCode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="street" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aptNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Room">
    <eStructuralFeatures xsi:type="ecore:EReference" name="SensorDevice" eType="#//SensorDevice" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ActuatorDevice" eType="#//ActuatorDevice" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RelationalTerm" eType="#//RelationalTerm" containment="false" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Device" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceStatus" eType="#//DeviceStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="BooleanExpression" eType="#//BooleanExpression" containment="true" lowerBound="0" upperBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SensorDevice">
    <eSuperTypes href="#//Device"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SensorReading" eType="#//SensorReading" containment="false" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RelationalTerm" eType="#//RelationalTerm" containment="false" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActuatorDevice">
    <eSuperTypes href="#//Device"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ControlCommand" eType="#//ControlCommand" containment="false" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RelationalTerm" eType="#//RelationalTerm" containment="false" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityLog">
    <eStructuralFeatures xsi:type="ecore:EReference" name="SensorReading" eType="#//SensorReading" containment="true" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ControlCommand" eType="#//ControlCommand" containment="true" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuntimeElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timestamp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ETime"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SensorReading">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RelationalTerm" eType="#//RelationalTerm" containment="false" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControlCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="commandType" eType="#//CommandType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="commandStatus" eType="#//CommandStatus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="RelationalTerm" eType="#//RelationalTerm" containment="false" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlertRule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ruleStatus" eType="#//RuleStatus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CommandSequence" eType="#//CommandSequence" containment="true" upperBound="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanExpression" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="NotExpression" eType="#//NotExpression" containment="false" lowerBound="0" upperBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="BinaryExpression" eType="#//BinaryExpression" containment="false" lowerBound="0" upperBound="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationalTerm">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NotExpression">
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="binaryOp" eType="#//BinaryOp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommandSequence">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ControlCommand" eType="#//ControlCommand" containment="true" lowerBound="0" upperBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CommandSequence" eType="#//CommandSequence" containment="false" upperBound="-1"/>
  </eClassifiers>
</ecore:EPackage>