---
title: "analysis"
output: html_document
date: "2024-12-07"
editor_options: 
  markdown: 
    wrap: 72
---

```{r}
library(readxl)
library(dplyr)
library(tidyr)
library(lme4)
library(lmerTest)
```

# Task Generation and 33%PSM

## Import Data

```{r cars}
df_long <- read_excel('IFT6253LLMAssistantEvaluation.xlsx', skip=1, sheet = "TaskGen_PSM")

colnames(df_long)[3] <- "Shot_Example"

colnames(df_long)[7] <- "Class_Precision"
colnames(df_long)[8] <- "Class_Recall"
colnames(df_long)[9] <- "Class_F1"

colnames(df_long)[10] <- "Attr_Precision"
colnames(df_long)[11] <- "Attr_Recall"
colnames(df_long)[12] <- "Attr_F1"

colnames(df_long)[13] <- "Rel_Precision"
colnames(df_long)[14] <- "Rel_Recall"
colnames(df_long)[15] <- "Rel_F1"

df_long$Combination <- factor(df_long$Combination)
df_long$Shot_Example <- factor(df_long$Shot_Example)
df_long$DSL2Gen <- factor(df_long$DSL2Gen)
df_long$TaskGenMethod <- factor(df_long$TaskGenMethod)
df_long$PSM <- factor(df_long$PSM)

head(df_long)
```

## Preprocess

```{r}
df_long <- df_long %>%
  pivot_longer(
    cols = colnames(df_long)[7:15], # Select relevant columns
    names_to = c("ElementType", ".value"),
    names_sep = "_"
  )

head(df_long)
```

## Box plots

```{r}
library(ggplot2)

df <- df_long %>%
  pivot_longer(cols = c(Precision, Recall, F1),
               names_to = "Metric",
               values_to = "Score")
head(df)

ggplot(df, aes(x = Metric, y = Score, fill = Metric)) +
  geom_boxplot() +
  facet_wrap(~TaskGenMethod) +
  labs(title = "Score by Task Generation mode and Metrics") +
  theme_minimal() +
  theme(legend.position = "none")
ggplot(df, aes(x = Metric, y = Score, fill = Metric)) +
  geom_boxplot() +
  facet_wrap(~PSM) +
  labs(title = "Score with and without PSM and Metrics") +
  theme_minimal() +
  theme(legend.position = "none")
```

## Analysis

### Class

#### Precision

```{r}
library(lme4)
library(lmerTest)
library(car)
library(emmeans)

df <- df_long[df_long$ElementType == "Class", ]
head(df)

class_precision <- lm(Precision ~ TaskGenMethod * PSM + DSL2Gen + Shot_Example, data = df)
summary(class_precision)
print("----------------------")

qqnorm(residuals(class_precision))
qqline(residuals(class_precision),col="red")

leveneTest(residuals(class_precision) ~ TaskGenMethod * PSM, data=df)
print("----------------------")

print("TaskGenMethod")
emmeans(class_precision, pairwise ~ TaskGenMethod)
print("PSM")
emmeans(class_precision, pairwise ~ PSM)
print("TaskGenMethod | PSM")
emmeans(class_precision, pairwise ~ TaskGenMethod | PSM)
```

#### Recall

```{r}
df <- df_long[df_long$ElementType == "Class", ]
head(df)

class_recall <- lm(Recall ~ TaskGenMethod * PSM + DSL2Gen + Shot_Example, data = df)
summary(class_recall)
print("----------------------")

qqnorm(residuals(class_recall))
qqline(residuals(class_recall),col="red")

leveneTest(residuals(class_recall) ~ TaskGenMethod * PSM , data=df)
print("----------------------")

print("TaskGenMethod")
emmeans(class_recall, pairwise ~ TaskGenMethod)
print("PSM")
emmeans(class_recall, pairwise ~ PSM)
print("TaskGenMethod | PSM")
emmeans(class_recall, pairwise ~ TaskGenMethod | PSM)
```

#### F1

```{r}
df <- df_long[df_long$ElementType == "Class", ]
head(df)

class_f1 <- lm(F1 ~ TaskGenMethod * PSM + DSL2Gen + Shot_Example, data = df)
summary(class_f1)
print("----------------------")

qqnorm(residuals(class_f1))
qqline(residuals(class_f1),col="red")

leveneTest(residuals(class_f1) ~ TaskGenMethod * PSM , data=df)
print("----------------------")

print("TaskGenMethod")
emmeans(class_f1, pairwise ~ TaskGenMethod)
print("PSM")
emmeans(class_f1, pairwise ~ PSM)
print("TaskGenMethod | PSM")
emmeans(class_f1, pairwise ~ TaskGenMethod | PSM)
```

### Attr

#### Precision

```{r}
df <- df_long[df_long$ElementType == "Attr", ]
head(df)

attr_precision <- lm(Precision ~ TaskGenMethod * PSM + DSL2Gen + Shot_Example, data = df)
summary(attr_precision)
print("----------------------")

qqnorm(residuals(attr_precision))
qqline(residuals(attr_precision),col="red")

leveneTest(residuals(attr_precision) ~ TaskGenMethod * PSM, data=df)
print("----------------------")

print("TaskGenMethod")
emmeans(attr_precision, pairwise ~ TaskGenMethod)
print("PSM")
emmeans(attr_precision, pairwise ~ PSM)
print("TaskGenMethod | PSM")
emmeans(attr_precision, pairwise ~ TaskGenMethod | PSM)
```

#### Recall

```{r}
library(emmeans)

df <- df_long[df_long$ElementType == "Attr", ]
head(df)

attr_recall <- lm(Recall ~ TaskGenMethod * PSM + DSL2Gen + Shot_Example, data = df)
summary(attr_recall)
print("----------------------")

qqnorm(residuals(attr_recall))
qqline(residuals(attr_recall),col="red")

leveneTest(residuals(attr_recall) ~ TaskGenMethod * PSM, data=df)
print("----------------------")

print("TaskGenMethod")
emmeans(attr_recall, pairwise ~ TaskGenMethod)
print("PSM")
emmeans(attr_recall, pairwise ~ PSM)
print("TaskGenMethod | PSM")
emmeans(attr_recall, pairwise ~ TaskGenMethod | PSM)
```

#### F1

```{r}
library(emmeans)

df <- df_long[df_long$ElementType == "Attr", ]
head(df)

attr_f1 <- lm(F1 ~ TaskGenMethod * PSM + DSL2Gen + Shot_Example, data = df)
summary(attr_f1)
print("----------------------")

qqnorm(residuals(attr_f1))
qqline(residuals(attr_f1),col="red")

leveneTest(residuals(attr_f1) ~ TaskGenMethod * PSM, data=df)
print("----------------------")

print("TaskGenMethod")
emmeans(attr_f1, pairwise ~ TaskGenMethod)
print("PSM")
emmeans(attr_f1, pairwise ~ PSM)
print("TaskGenMethod | PSM")
emmeans(attr_f1, pairwise ~ TaskGenMethod | PSM)
```

### Rel

#### Precision

```{r}
df <- df_long[df_long$ElementType == "Rel", ]
head(df)

rel_precision <- lm(Precision ~ TaskGenMethod * PSM + DSL2Gen + Shot_Example, data = df)
summary(rel_precision)
print("----------------------")

qqnorm(residuals(rel_precision))
qqline(residuals(rel_precision),col="red")

leveneTest(residuals(rel_precision) ~ TaskGenMethod * PSM, data=df)
print("----------------------")

print("TaskGenMethod")
emmeans(rel_precision, pairwise ~ TaskGenMethod)
print("PSM")
emmeans(rel_precision, pairwise ~ PSM)
print("TaskGenMethod | PSM")
emmeans(rel_precision, pairwise ~ TaskGenMethod | PSM)
```

#### Recall

```{r}
df <- df_long[df_long$ElementType == "Rel", ]
head(df)

rel_recall <- lm(Recall ~ TaskGenMethod * PSM + DSL2Gen + Shot_Example, data = df)
summary(rel_recall)
print("----------------------")

qqnorm(residuals(rel_recall))
qqline(residuals(rel_recall),col="red")

leveneTest(residuals(rel_recall) ~ TaskGenMethod * PSM, data=df)
print("----------------------")

print("TaskGenMethod")
emmeans(rel_recall, pairwise ~ TaskGenMethod)
print("PSM")
emmeans(rel_recall, pairwise ~ PSM)
print("TaskGenMethod | PSM")
emmeans(rel_recall, pairwise ~ TaskGenMethod | PSM)
```

#### F1

```{r}
df <- df_long[df_long$ElementType == "Rel", ]
head(df)

rel_f1 <- lm(F1 ~ TaskGenMethod * PSM + DSL2Gen + Shot_Example, data = df)
summary(rel_f1)
print("----------------------")

qqnorm(residuals(rel_f1))
qqline(residuals(rel_f1),col="red")

leveneTest(residuals(rel_f1) ~ TaskGenMethod * PSM, data=df)
print("----------------------")

print("TaskGenMethod")
emmeans(rel_f1, pairwise ~ TaskGenMethod)
print("PSM")
emmeans(rel_f1, pairwise ~ PSM)
print("TaskGenMethod | PSM")
emmeans(rel_f1, pairwise ~ TaskGenMethod | PSM)
```

# Comparison Partial Solution Model

## Import Data

```{r}
df_long <- read_excel('IFT6253LLMAssistantEvaluation.xlsx', skip=1, sheet = "PSM")

colnames(df_long)[3] <- "Shot_Example"

colnames(df_long)[6] <- "Class_Precision"
colnames(df_long)[7] <- "Class_Recall"
colnames(df_long)[8] <- "Class_F1"

colnames(df_long)[9] <- "Attr_Precision"
colnames(df_long)[10] <- "Attr_Recall"
colnames(df_long)[11] <- "Attr_F1"

colnames(df_long)[12] <- "Rel_Precision"
colnames(df_long)[13] <- "Rel_Recall"
colnames(df_long)[14] <- "Rel_F1"

df_long$Combination <- factor(df_long$Combination)
df_long$Shot_Example <- factor(df_long$Shot_Example)
df_long$DSL2Gen <- factor(df_long$DSL2Gen)
df_long$PSM <- factor(df_long$PSM)

head(df_long)
```

## Pre process

```{r}
df_long <- df_long %>%
  pivot_longer(
    cols = colnames(df_long)[6:14], # Select relevant columns
    names_to = c("ElementType", ".value"),
    names_sep = "_"
  )

head(df_long)
```

## Box Plots

```{r}
library(ggplot2)

df <- df_long %>%
  pivot_longer(cols = c(Precision, Recall, F1),
               names_to = "Metric",
               values_to = "Score")
head(df)

ggplot(df, aes(x = Metric, y = Score, fill = Metric)) +
  geom_boxplot() +
  facet_wrap(~PSM, nrow=1) +
  labs(title = "Score with and without PSM and Metrics") +
  theme_minimal() +
  theme(legend.position = "none")
```

## Analysis

### Class

#### Precision

```{r}
library(lme4)
library(lmerTest)
library(car)
library(emmeans)

df <- df_long[df_long$ElementType == "Class", ]
head(df)

class_precision <- lm(Precision ~ PSM + DSL2Gen + Shot_Example, data = df)
summary(class_precision)
print("----------------------")

qqnorm(residuals(class_precision))
qqline(residuals(class_precision),col="red")

leveneTest(residuals(class_precision) ~ PSM, data=df)
print("----------------------")

print("PSM")
emmeans_results <- emmeans(class_precision, pairwise ~ PSM)
emmeans_results$emmeans
contrast_results <- contrast(emmeans_results, method = "trt.vs.ctrl", ref = 1)
summary(contrast_results)
```

#### Recall

```{r}
library(lme4)
library(lmerTest)
library(car)
library(emmeans)

df <- df_long[df_long$ElementType == "Class", ]
head(df)

class_recall <- lm(Recall ~ PSM + DSL2Gen + Shot_Example, data = df)
summary(class_recall)
print("----------------------")

qqnorm(residuals(class_recall))
qqline(residuals(class_recall),col="red")

leveneTest(residuals(class_recall) ~ PSM, data=df)
print("----------------------")

print("PSM")
emmeans_results <- emmeans(class_recall, pairwise ~ PSM)
emmeans_results$emmeans
contrast_results <- contrast(emmeans_results, method = "trt.vs.ctrl", ref = 1)
summary(contrast_results)
```

#### F1

```{r}
library(lme4)
library(lmerTest)
library(car)
library(emmeans)

df <- df_long[df_long$ElementType == "Class", ]
head(df)

class_f1 <- lm(F1 ~ PSM + DSL2Gen + Shot_Example, data = df)
summary(class_f1)
print("----------------------")

qqnorm(residuals(class_f1))
qqline(residuals(class_f1),col="red")

leveneTest(residuals(class_f1) ~ PSM, data=df)
print("----------------------")

print("PSM")
emmeans_results <- emmeans(class_f1, pairwise ~ PSM)
emmeans_results$emmeans
contrast_results <- contrast(emmeans_results, method = "trt.vs.ctrl", ref = 1)
summary(contrast_results)

print("DSL2Gen ")
emmeans(class_f1, pairwise ~ DSL2Gen)$contrast
```

### Attr

#### Precision

```{r}
library(lme4)
library(lmerTest)
library(car)
library(emmeans)

df <- df_long[df_long$ElementType == "Attr", ]
head(df)

attr_precision <- lm(Precision ~ PSM + DSL2Gen + Shot_Example, data = df)
summary(attr_precision)
print("----------------------")

qqnorm(residuals(attr_precision))
qqline(residuals(attr_precision),col="red")

leveneTest(residuals(attr_precision) ~ PSM, data=df)
print("----------------------")

print("PSM")
emmeans_results <- emmeans(attr_precision, pairwise ~ PSM)
emmeans_results$emmeans
contrast_results <- contrast(emmeans_results, method = "trt.vs.ctrl", ref = 1)
summary(contrast_results)
```

#### Recall

```{r}
library(lme4)
library(lmerTest)
library(car)
library(emmeans)

df <- df_long[df_long$ElementType == "Attr", ]
head(df)

attr_recall <- lm(Recall ~ PSM + DSL2Gen + Shot_Example, data = df)
summary(attr_recall)
print("----------------------")

qqnorm(residuals(attr_recall))
qqline(residuals(attr_recall),col="red")

leveneTest(residuals(attr_recall) ~ PSM, data=df)
print("----------------------")

print("PSM")
emmeans_results <- emmeans(attr_recall, pairwise ~ PSM)
emmeans_results$emmeans
contrast_results <- contrast(emmeans_results, method = "trt.vs.ctrl", ref = 1)
summary(contrast_results)
```

#### F1

```{r}
library(lme4)
library(lmerTest)
library(car)
library(emmeans)

df <- df_long[df_long$ElementType == "Attr", ]
head(df)

attr_f1 <- lm(F1 ~ PSM + DSL2Gen + Shot_Example, data = df)
summary(attr_f1)
print("----------------------")

qqnorm(residuals(attr_f1))
qqline(residuals(attr_f1),col="red")

leveneTest(residuals(attr_f1) ~ PSM, data=df)
print("----------------------")

print("PSM")
emmeans_results <- emmeans(attr_f1, pairwise ~ PSM)
emmeans_results$emmeans
contrast_results <- contrast(emmeans_results, method = "trt.vs.ctrl", ref = 1)
summary(contrast_results)
```

### Rel

#### Precision

```{r}
library(lme4)
library(lmerTest)
library(car)
library(emmeans)

df <- df_long[df_long$ElementType == "Rel", ]
head(df)

rel_precision <- lm(Precision ~ PSM + DSL2Gen + Shot_Example, data = df)
summary(rel_precision)
print("----------------------")

qqnorm(residuals(rel_precision))
qqline(residuals(rel_precision),col="red")

leveneTest(residuals(rel_precision) ~ PSM, data=df)
print("----------------------")

print("PSM")
emmeans_results <- emmeans(rel_precision, pairwise ~ PSM)
emmeans_results$emmeans
contrast_results <- contrast(emmeans_results, method = "trt.vs.ctrl", ref = 1)
summary(contrast_results)
```

#### Recall

```{r}
library(lme4)
library(lmerTest)
library(car)
library(emmeans)

df <- df_long[df_long$ElementType == "Rel", ]
head(df)

rel_recall <- lm(Recall ~ PSM + DSL2Gen + Shot_Example, data = df)
summary(rel_recall)
print("----------------------")

qqnorm(residuals(rel_recall))
qqline(residuals(rel_recall),col="red")

leveneTest(residuals(rel_recall) ~ PSM, data=df)
print("----------------------")

print("PSM")
emmeans_results <- emmeans(rel_recall, pairwise ~ PSM)
emmeans_results$emmeans
contrast_results <- contrast(emmeans_results, method = "trt.vs.ctrl", ref = 1)
summary(contrast_results)
```

#### F1

```{r}
library(lme4)
library(lmerTest)
library(car)
library(emmeans)

df <- df_long[df_long$ElementType == "Rel", ]
head(df)

rel_f1 <- lm(F1 ~ PSM + DSL2Gen + Shot_Example, data = df)
summary(rel_f1)
print("----------------------")

qqnorm(residuals(rel_f1))
qqline(residuals(rel_f1),col="red")

leveneTest(residuals(rel_f1) ~ PSM, data=df)
print("----------------------")

print("PSM")
emmeans_results <- emmeans(rel_f1, pairwise ~ PSM)
emmeans_results$emmeans
contrast_results <- contrast(emmeans_results, method = "trt.vs.ctrl", ref = 1)
summary(contrast_results)
```

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)

df <- data.frame(
    Completeness_Ratio = c("40%", "33%", "25%", "0"),
    Class_Precision = c(0.93, 0.89, 0.89, 0.82),
    Class_Recall = c(0.88, 0.77, 0.73, 0.69),
    Class_F1 = c(0.90, 0.82, 0.79, 0.72),
    Attribute_Precision = c(0.84, 0.87, 0.86, 0.80),
    Attribute_Recall = c(0.81, 0.65, 0.55, 0.59),
    Attribute_F1 = c(0.82, 0.74, 0.67, 0.67),
    Relationship_Precision = c(0.84, 0.74, 0.79, 0.51),
    Relationship_Recall = c(0.75, 0.68, 0.62, 0.50),
    Relationship_F1 = c(0.79, 0.71, 0.69, 0.49)
)

df <- df %>%
  pivot_longer(
    cols = colnames(df)[2:10], # Select relevant columns
    names_to = c("ElementType", ".value"),
    names_sep = "_"
  )

df <- gather(df, key = "Metric", value = "Value", Precision, Recall, F1)

ggplot(df, aes(x = Completeness_Ratio, y = Value, color = Metric, group = Metric)) +
    geom_line(size = 1) +  # Add lines
    geom_point()+
    scale_y_continuous(limits = c(0, 1)) +
    facet_wrap(~ ElementType, scales = "free_y") +
    theme_minimal() +      # Apply a minimal theme
    labs(
        title = "ElementType scores across level of Completeness in the PSM",
        x = "Completeness of the PSM ratio",
        y = "F1 Score",
        color = "ElementType"
    )
```

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)

df <- data.frame(
    Completeness_Ratio = c("40%", "33%", "25%"),
    Class_Precision = c(0.11, 0.07, 0.07),
    Class_Recall = c(0.19, 0.08, 0.04),
    Class_F1 = c(0.18, 0.10, 0.07),
    Attribute_Precision = c(0.04, 0.07, 0.06),
    Attribute_Recall = c(0.22, 0.06, -0.04),
    Attribute_F1 = c(0.15, 0.07, 0),
    Relationship_Precision = c(0.33, 0.23, 0.28),
    Relationship_Recall = c(0.25, 0.18, 0.12),
    Relationship_F1 = c(0.30, 0.21, 0.20)
)

df <- df %>%
  pivot_longer(
    cols = colnames(df)[2:10], # Select relevant columns
    names_to = c("ElementType", ".value"),
    names_sep = "_"
  )

df <- gather(df, key = "Metric", value = "Value", Precision, Recall, F1)

ggplot(df, aes(x = Completeness_Ratio, y = Value, color = Metric, group = Metric)) +
    geom_line(size = 1) +  # Add lines
    geom_point()+
    facet_wrap(~ ElementType, scales = "free_y") +
    theme_minimal() +      # Apply a minimal theme
    labs(
        title = "Class, Attribute across level of Completeness in the PSM",
        x = "Completeness of the PSM ratio",
        color = "ElementType"
    )
```

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)

gradient_df <- data.frame(
    Completeness_Ratio = c("40%", "33%", "25%"),
    Class_Precision = c(0.04, 0, 0.07),
    Class_Recall = c(0.11, 0.04, 0.04),
    Class_F1 = c(0.08, 0.03, 0.07),
    Attribute_Precision = c(-0.03, 0.01, 0.06),
    Attribute_Recall = c(0.16, 0.10, -0.04),
    Attribute_F1 = c(0.11, 0.07, 0),
    Relationship_Precision = c(0.1, -0.05, 0.28),
    Relationship_Recall = c(0.07, 0.06, 0.12),
    Relationship_F1 = c(0.08, 0.02, 0.2)
)

gradient_df <- gradient_df %>%
  pivot_longer(
    cols = colnames(gradient_df)[2:10], # Select relevant columns
    names_to = c("ElementType", ".value"),
    names_sep = "_"
  )

gradient_df <- gather(gradient_df, key = "Metric", value = "Value", Precision, Recall, F1)

ggplot(gradient_df, aes(x = Completeness_Ratio, y = Value, color = Metric, group = Metric)) +
    geom_line(size = 1) +  # Add lines
    geom_point()+
    facet_wrap(~ ElementType) +
    theme_minimal() +      # Apply a minimal theme
    labs(
        title = "Metrics increase across level of Completeness in the PSM",
        x = "Completeness of the PSM ratio",
        y = "Score",
        color = "ElementType"
    )
```
